import React from "react";
import moment from "moment";
import { useNavigate } from "react-router-dom";

function Card({ info }) {
  let navigate = useNavigate();
  return (
    <div
      onClick={() => navigate("/article/" + info.id)}
      className=" bg-white rounded-lg drop-shadow-[0_0_6px_rgba(0,0,0,0.10)] px-4 py-4 flex flex-col
      w-100 hover:text-teal-700
      hover: border-b-8 border-white hover:border-teal-700 duration-500 ease-in-out cursor-pointer"
    >
      <div className="grow">
        <div className="font-medium text-lg">{info.title}</div>
        <div className="font-medium text-sm text-gray-600">{info.author}</div>
        <div className="py-3 flex flex-wrap gap-2">
          {info.tags.slice(0, 5).map((tag) => {
            return (
              <span className="text-sm text-gray-500 bg-gray-100 rounded-full px-3 py-1">
                {tag.tag}
              </span>
            );
          })}
        </div>
      </div>
      <div className="flex justify-between">
        <span className="text-sm text-gray-500">
          Generated by {info.generator}
        </span>
        <span className="text-sm text-gray-500">
          {moment(info.date).format("MMM Do YY")}
        </span>
      </div>
    </div>
  );
}

export default Card;
